[package]
name = "rufetch-ubuntu"
version = "0.1.0"
authors = ["DumbMahreeo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
opt-level = "s"
